import { 
  HeadhunterClient, 
  HeadhunterLead, 
  HeadhunterJob, 
  HeadhunterCandidate, 
  HeadhunterInterview, 
  HeadhunterHiring, 
  HeadhunterCommission, 
  HeadhunterFinanceItem, 
  HeadhunterExpense, 
  HeadhunterEvent, 
  HeadhunterContract 
} from './types';

export const MOCK_HEADHUNTER_CLIENTS: HeadhunterClient[] = [
  {
    id: 'cli-101',
    empresaId: 'emp-001',
    criadoPor: 'Carlos Headhunter',
    criadoEm: '2026-01-10',
    status: 'Ativo',
    razaoSocial: 'Nexus Tech S.A. Soluções em Software',
    nomeFantasia: 'Grupo Nexus Tech',
    cnpj: '12.345.678/0001-90',
    segmento: 'Tecnologia & SaaS',
    porte: 'Grande',
    qtdFuncionarios: 350,
    responsavel: 'Luciana Martins',
    cargoResponsavel: 'VP de Recursos Humanos',
    telefone: '(11) 3456-7890',
    whatsapp: '(11) 98765-4321',
    email: 'l.martins@nexustech.com.br',
    site: 'https://nexustech.com.br',
    endereco: 'Av. Paulista, 1000, Cj 1201 - Bela Vista, São Paulo - SP',
    valorPadraoVaga: 18000,
    comissaoNegociadaPercent: 20,
    formaCobranca: 'Sucesso + Retainer (50/50)',
    prazoPagamentoDias: 30,
    contratoAtivo: true,
    historico: [
      { data: '2026-02-01', descricao: 'Alinhamento do contrato anual de recrutamento executivo.', autor: 'Carlos' },
      { data: '2026-02-15', descricao: 'Fechamento da vaga de CTO com comissão de R$ 36.000.', autor: 'Carlos' }
    ],
    reunioesCount: 8,
    pendenciasCount: 1,
    vagasCount: 3
  },
  {
    id: 'cli-102',
    empresaId: 'emp-001',
    criadoPor: 'Mariana Souza',
    criadoEm: '2026-02-05',
    status: 'Ativo',
    razaoSocial: 'Vanguard Biopharma Indústria e Comércio',
    nomeFantasia: 'Vanguard Pharma',
    cnpj: '98.765.432/0001-11',
    segmento: 'Farmacêutica & Saúde',
    porte: 'Médio',
    qtdFuncionarios: 180,
    responsavel: 'Roberto Alencar',
    cargoResponsavel: 'Diretor Geral',
    telefone: '(11) 4004-9988',
    whatsapp: '(11) 99123-8877',
    email: 'r.alencar@vanguardpharma.com',
    site: 'https://vanguardpharma.com',
    endereco: 'Rua Funchal, 418, 8º andar - Vila Olímpia, São Paulo - SP',
    valorPadraoVaga: 22000,
    comissaoNegociadaPercent: 22,
    formaCobranca: 'Exclusividade 100% no Sucesso',
    prazoPagamentoDias: 15,
    contratoAtivo: true,
    historico: [
      { data: '2026-02-10', descricao: 'Início da busca para Diretor Industrial.', autor: 'Mariana' }
    ],
    reunioesCount: 5,
    pendenciasCount: 0,
    vagasCount: 2
  },
  {
    id: 'cli-103',
    empresaId: 'emp-001',
    criadoPor: 'Carlos Headhunter',
    criadoEm: '2026-03-01',
    status: 'Inativo',
    razaoSocial: 'Inova Logistics & Supply Chain Ltda',
    nomeFantasia: 'Inova Logística',
    cnpj: '45.112.334/0001-55',
    segmento: 'Logística & Transporte',
    porte: 'Pequeno',
    qtdFuncionarios: 45,
    responsavel: 'Fernanda Lima',
    cargoResponsavel: 'Gerente de Gente & Gestão',
    telefone: '(11) 2233-4455',
    whatsapp: '(11) 97788-9900',
    email: 'f.lima@inovalog.com.br',
    site: 'https://inovalog.com.br',
    endereco: 'Rodovia Anhanguera, Km 25 - Jundiaí - SP',
    valorPadraoVaga: 12000,
    comissaoNegociadaPercent: 18,
    formaCobranca: 'Sucesso',
    prazoPagamentoDias: 30,
    contratoAtivo: false,
    historico: [
      { data: '2026-03-02', descricao: 'Congelamento temporário das contratações por reestruturação.', autor: 'Carlos' }
    ],
    reunioesCount: 2,
    pendenciasCount: 2,
    vagasCount: 1
  }
];

export const MOCK_HEADHUNTER_LEADS: HeadhunterLead[] = [
  {
    id: 'lead-201',
    empresaId: 'emp-001',
    criadoPor: 'Carlos Headhunter',
    criadoEm: '2026-03-10',
    status: 'Em Andamento',
    empresa: 'Apex Capital Investimentos',
    contato: 'Marcelo Nogueira (CEO)',
    email: 'm.nogueira@apexcapital.com.br',
    telefone: '(11) 98877-6655',
    origem: 'Outbound / LinkedIn Executive',
    consultor: 'Carlos Headhunter',
    etapa: 'Proposta enviada',
    valorPrevisto: 35000,
    probabilidadePercent: 75,
    proximoContato: '2026-03-25',
    historico: [
      { data: '2026-03-10', anotacao: 'Primeira conversa via LinkedIn com CEO solicitando busca para VP de Riscos.', autor: 'Carlos' },
      { data: '2026-03-15', anotacao: 'Apresentação da proposta comercial enviada por e-mail.', autor: 'Carlos' }
    ],
    observacoes: 'Cliente busca perfil sênior de mercado com passagem por Faria Lima.'
  },
  {
    id: 'lead-202',
    empresaId: 'emp-001',
    criadoPor: 'Mariana Souza',
    criadoEm: '2026-03-12',
    status: 'Em Andamento',
    empresa: 'Solaria Energy Brasil',
    contato: 'Beatriz Castro (Head de HR)',
    email: 'b.castro@solariaenergy.com',
    telefone: '(19) 99112-2233',
    origem: 'Indicação de Cliente',
    consultor: 'Mariana Souza',
    etapa: 'Negociação',
    valorPrevisto: 28000,
    probabilidadePercent: 90,
    proximoContato: '2026-03-22',
    historico: [
      { data: '2026-03-12', anotacao: 'Reunião virtual de alinhamento e ajuste de percentual de comissão (20%).', autor: 'Mariana' }
    ],
    observacoes: 'Contrato aditivo em revisão pelo jurídico do cliente.'
  }
];

export const MOCK_HEADHUNTER_JOBS: HeadhunterJob[] = [
  {
    id: 'job-301',
    empresaId: 'emp-001',
    criadoPor: 'Carlos Headhunter',
    criadoEm: '2026-02-01',
    status: 'Em Andamento',
    clienteId: 'cli-101',
    clienteNome: 'Grupo Nexus Tech',
    consultorResponsavel: 'Carlos Headhunter',
    recrutador: 'Ana Clara Recrutadora',
    cargo: 'Head of Growth & Performance Marketing',
    descricao: 'Liderar a estratégia de aquisição de clientes B2B SaaS, gestão de orçamento de mídia performance e expansão latam.',
    requisitos: ['Inglês fluente', 'Mais de 8 anos em Growth B2B SaaS', 'Domínio em CAC, LTV e Churn analytics'],
    salario: 'R$ 25.000 - R$ 30.000/mês + Bônus',
    salarioValor: 28000,
    tipoContratacao: 'Executive',
    local: 'São Paulo - SP (Híbrido)',
    dataAbertura: '2026-02-01',
    dataPrevista: '2026-03-30',
    slaDias: 45,
    prioridade: 'Alta',
    valorNegociado: 28000,
    valorVaga: 28000,
    percentualComissao: 20,
    comissaoCalculada: 56000,
    qtdVagas: 1,
    candidatosIds: ['cand-401', 'cand-402', 'cand-403'],
    documentosCount: 3,
    historico: [
      { data: '2026-02-01', evento: 'Vaga aberta no sistema e alinhada com VP de RH.', autor: 'Carlos' },
      { data: '2026-02-10', evento: 'Shortlist de 3 candidatos enviada ao cliente.', autor: 'Carlos' }
    ]
  },
  {
    id: 'job-302',
    empresaId: 'emp-001',
    criadoPor: 'Mariana Souza',
    criadoEm: '2026-02-10',
    status: 'Em Andamento',
    clienteId: 'cli-102',
    clienteNome: 'Vanguard Pharma',
    consultorResponsavel: 'Mariana Souza',
    recrutador: 'Felipe Recrutador',
    cargo: 'Diretor Industrial e Regulatório',
    descricao: 'Gestão da planta fabril em Jundiaí, comitê de compliance da ANVISA e liderança de 120 profissionais.',
    requisitos: ['Graduação em Engenharia Química ou Farmácia', 'MBA em Gestão Industrial', 'Domínio de normas ANVISA'],
    salario: 'R$ 38.000/mês + Veículo da Cia',
    salarioValor: 38000,
    tipoContratacao: 'Executive',
    local: 'Jundiaí - SP (Presencial)',
    dataAbertura: '2026-02-10',
    dataPrevista: '2026-04-10',
    slaDias: 60,
    prioridade: 'Urgente',
    valorNegociado: 38000,
    valorVaga: 38000,
    percentualComissao: 22,
    comissaoCalculada: 83600,
    qtdVagas: 1,
    candidatosIds: ['cand-404', 'cand-405'],
    documentosCount: 2,
    historico: [
      { data: '2026-02-10', evento: 'Mapeamento confidencial de mercado iniciado.', autor: 'Mariana' }
    ]
  },
  {
    id: 'job-303',
    empresaId: 'emp-001',
    criadoPor: 'Carlos Headhunter',
    criadoEm: '2026-01-05',
    status: 'Fechada',
    clienteId: 'cli-101',
    clienteNome: 'Grupo Nexus Tech',
    consultorResponsavel: 'Carlos Headhunter',
    recrutador: 'Ana Clara Recrutadora',
    cargo: 'Chief Technology Officer (CTO)',
    descricao: 'Liderar o time de engenharia de software e arquitetura de inteligência artificial corporativa.',
    requisitos: ['Experiência prévia como CTO ou VP of Engineering em SaaS escala global.'],
    salario: 'R$ 45.000/mês + Equity',
    salarioValor: 45000,
    tipoContratacao: 'Executive',
    local: 'São Paulo - SP',
    dataAbertura: '2026-01-05',
    dataPrevista: '2026-02-28',
    slaDias: 45,
    prioridade: 'Alta',
    valorNegociado: 45000,
    valorVaga: 45000,
    percentualComissao: 20,
    comissaoCalculada: 90000,
    qtdVagas: 1,
    candidatosIds: ['cand-406'],
    documentosCount: 5,
    historico: [
      { data: '2026-02-20', evento: 'Candidato aprovado e contrato de trabalho assinado.', autor: 'Carlos' },
      { data: '2026-02-22', evento: 'Vaga finalizada com sucesso. Faturamento de R$ 90.000 gerado.', autor: 'Carlos' }
    ]
  }
];

export const MOCK_HEADHUNTER_CANDIDATES: HeadhunterCandidate[] = [
  {
    id: 'cand-401',
    empresaId: 'emp-001',
    criadoPor: 'Carlos Headhunter',
    criadoEm: '2026-02-05',
    status: 'Ativo',
    vagaId: 'job-301',
    vagaTitulo: 'Head of Growth & Performance Marketing',
    clienteNome: 'Grupo Nexus Tech',
    nome: 'Eduardo Albuquerque',
    email: 'eduardo.growth@gmail.com',
    telefone: '(11) 99887-1122',
    cargoAtual: 'Senior Growth Manager na VTEX',
    salarioAtual: 22000,
    pretensaoSalarial: 28000,
    curriculoTexto: 'Líder de Growth com 10 anos de experiência em escala B2B SaaS Latam. Experiência em VTEX e Resultados Digitais.',
    compatibilidadePercent: 94,
    triagemIaScore: 95,
    triagemIaParecer: 'Excelente aderência aos requisitos de Growth B2B, fluência em inglês comprovada e forte tração de métricas de aquisição.',
    triagemRhStatus: 'Aprovado Triagem RH',
    parecerTecnico: 'Candidato demonstra excelente senioridade executiva e visão analítica sobre funil de vendas B2B.',
    etapaPipeline: 'Entrevista Cliente',
    historico: [
      { data: '2026-02-05', evento: 'Triagem inicial por IA concluída com 95% de afinidade.' },
      { data: '2026-02-12', evento: 'Entrevista técnica com o Headhunter realizada.' }
    ],
    linhaDoTempo: [
      { data: '2026-02-05', titulo: 'Mapeado e Abordado', detalhe: 'Contato ativo via LinkedIn Executive' },
      { data: '2026-02-12', titulo: 'Entrevista Headhunter', detalhe: 'Aprovado com parecer 9.5/10' },
      { data: '2026-02-18', titulo: 'Apresentado ao Cliente', detalhe: 'Agendado entrevista com VP de RH' }
    ]
  },
  {
    id: 'cand-402',
    empresaId: 'emp-001',
    criadoPor: 'Ana Clara Recrutadora',
    criadoEm: '2026-02-07',
    status: 'Ativo',
    vagaId: 'job-301',
    vagaTitulo: 'Head of Growth & Performance Marketing',
    clienteNome: 'Grupo Nexus Tech',
    nome: 'Camila Guimarães',
    email: 'camila.marketing@outlook.com',
    telefone: '(11) 98711-2233',
    cargoAtual: 'Head de Marketing na RD Station',
    salarioAtual: 24000,
    pretensaoSalarial: 30000,
    curriculoTexto: 'Especialista em Performance, SEO e Lead Gen para empresas de software.',
    compatibilidadePercent: 88,
    triagemIaScore: 89,
    triagemIaParecer: 'Forte background em inbound e branding, ligeiramente abaixo da meta de vivência em mídia paga de alta escala.',
    triagemRhStatus: 'Aprovado Triagem RH',
    parecerTecnico: 'Ótima comunicação e perfil de liderança colaborativa.',
    etapaPipeline: 'Entrevista Headhunter',
    historico: [
      { data: '2026-02-07', evento: 'Adicionado à pipeline de busca.' }
    ],
    linhaDoTempo: [
      { data: '2026-02-07', titulo: 'Candidatura Registrada', detalhe: 'Indicação direta' }
    ]
  },
  {
    id: 'cand-406',
    empresaId: 'emp-001',
    criadoPor: 'Carlos Headhunter',
    criadoEm: '2026-01-10',
    status: 'Contratado',
    vagaId: 'job-303',
    vagaTitulo: 'Chief Technology Officer (CTO)',
    clienteNome: 'Grupo Nexus Tech',
    nome: 'Alexandre Prado',
    email: 'alexandre.prado@ctoconsult.com',
    telefone: '(11) 99111-0000',
    cargoAtual: 'Ex-VP of Engineering no Nubank',
    salarioAtual: 40000,
    pretensaoSalarial: 45000,
    curriculoTexto: '20 anos liderando arquiteturas distribuídas e grandes times de tecnologia.',
    compatibilidadePercent: 98,
    triagemIaScore: 99,
    triagemIaParecer: 'Perfil excepcional alinhado integralmente aos desafios da vaga de CTO.',
    triagemRhStatus: 'Contratado',
    parecerTecnico: 'Candidato ideal aprovado por unanimidade no conselho da Nexus Tech.',
    etapaPipeline: 'Contratado',
    historico: [
      { data: '2026-02-20', evento: 'Proposta aceita e contratação confirmada.' }
    ],
    linhaDoTempo: [
      { data: '2026-01-10', titulo: 'Entrevista Inicial', detalhe: 'Headhunter Carlos' },
      { data: '2026-01-25', titulo: 'Apresentação no Conselho', detalhe: 'Pitch técnico impecável' },
      { data: '2026-02-20', titulo: 'Assinatura do Contrato', detalhe: 'Admitido em 01/03/2026' }
    ]
  }
];

export const MOCK_HEADHUNTER_INTERVIEWS: HeadhunterInterview[] = [
  {
    id: 'int-501',
    empresaId: 'emp-001',
    criadoPor: 'Carlos Headhunter',
    criadoEm: '2026-03-15',
    status: 'Agendada',
    clienteNome: 'Grupo Nexus Tech',
    vagaTitulo: 'Head of Growth & Performance Marketing',
    consultorNome: 'Carlos Headhunter',
    recrutadorNome: 'Ana Clara Recrutadora',
    candidatoNome: 'Eduardo Albuquerque',
    dataHora: '2026-03-24T15:00',
    modalidade: 'Online (Meet)',
    linkModalidade: 'https://meet.google.com/abc-defg-hij',
    pauta: 'Avaliação de case prático de alocação de orçamento de CAC e negociação salarial final com a VP Luciana.',
    feedback: 'Pendente realização.',
    parecer: 'Aguardando sessão com cliente.',
    resultado: 'Em Avaliação',
    proximaEtapa: 'Apresentação de Proposta Formal'
  },
  {
    id: 'int-502',
    empresaId: 'emp-001',
    criadoPor: 'Mariana Souza',
    criadoEm: '2026-03-10',
    status: 'Concluída',
    clienteNome: 'Vanguard Pharma',
    vagaTitulo: 'Diretor Industrial e Regulatório',
    consultorNome: 'Mariana Souza',
    recrutadorNome: 'Felipe Recrutador',
    candidatoNome: 'Luciano Seixas',
    dataHora: '2026-03-18T10:00',
    modalidade: 'Presencial',
    linkModalidade: 'Sede Vanguard Pharma - Sala de Reuniões 03',
    pauta: 'Validação de vivência prática com vistorias recentes da ANVISA e liderança fabril.',
    feedback: 'O candidato demonstrou segurança extrema e dominou o tema de compliance farmacêutico.',
    parecer: 'Recomendado fortemente para a segunda rodada com o CEO.',
    resultado: 'Aprovado',
    proximaEtapa: 'Entrevista Final com CEO Roberto Alencar'
  }
];

export const MOCK_HEADHUNTER_HIRINGS: HeadhunterHiring[] = [
  {
    id: 'hir-601',
    empresaId: 'emp-001',
    criadoPor: 'Carlos Headhunter',
    criadoEm: '2026-02-20',
    status: 'Concluído',
    candidatoId: 'cand-406',
    candidatoNome: 'Alexandre Prado',
    vagaId: 'job-303',
    vagaTitulo: 'Chief Technology Officer (CTO)',
    cargo: 'Chief Technology Officer (CTO)',
    clienteId: 'cli-101',
    clienteNome: 'Grupo Nexus Tech',
    consultorNome: 'Carlos Headhunter',
    dataContratacao: '2026-02-20',
    salarioFinal: 45000,
    receitaGerada: 90000,
    comissaoGerada: 18000,
    faturamentoGerado: true,
    garantiaAteData: '2026-05-20'
  },
  {
    id: 'hir-602',
    empresaId: 'emp-001',
    criadoPor: 'Carlos Headhunter',
    criadoEm: '2026-03-01',
    status: 'Concluído',
    candidatoId: 'cand-401',
    candidatoNome: 'Eduardo Albuquerque',
    vagaId: 'job-301',
    vagaTitulo: 'Head of Growth & Performance Marketing',
    cargo: 'Head of Growth',
    clienteId: 'cli-101',
    clienteNome: 'Grupo Nexus Tech',
    consultorNome: 'Carlos Headhunter',
    dataContratacao: '2026-03-01',
    salarioFinal: 28000,
    receitaGerada: 56000,
    comissaoGerada: 11200,
    faturamentoGerado: true,
    garantiaAteData: '2026-06-01'
  },
  {
    id: 'hir-603',
    empresaId: 'emp-001',
    criadoPor: 'Mariana Souza',
    criadoEm: '2026-03-10',
    status: 'Concluído',
    candidatoId: 'cand-405',
    candidatoNome: 'Luciano Seixas',
    vagaId: 'job-302',
    vagaTitulo: 'Diretor Industrial e Regulatório',
    cargo: 'Diretor Industrial',
    clienteId: 'cli-102',
    clienteNome: 'Vanguard Pharma',
    consultorNome: 'Mariana Souza',
    dataContratacao: '2026-03-10',
    salarioFinal: 38000,
    receitaGerada: 83600,
    comissaoGerada: 18392,
    faturamentoGerado: false,
    garantiaAteData: '2026-07-10'
  }
];

export const MOCK_HEADHUNTER_COMMISSIONS: HeadhunterCommission[] = [
  {
    id: 'com-701',
    empresaId: 'emp-001',
    criadoPor: 'Carlos Headhunter',
    criadoEm: '2026-02-22',
    status: 'Liberada',
    beneficiarioNome: 'Carlos Headhunter',
    clienteId: 'cli-101',
    clienteNome: 'Grupo Nexus Tech',
    vagaId: 'job-303',
    vagaTitulo: 'Chief Technology Officer (CTO)',
    consultorNome: 'Carlos Headhunter',
    tipoComissao: 'Comissão percentual',
    valorRecebidoVaga: 90000,
    percentual: 20,
    valorComissao: 18000,
    valorPago: 18000,
    dataPrevista: '2026-03-15',
    dataPagamento: '2026-03-14',
    situacao: 'Paga',
    regraLiberacao: 'cliente_pagou'
  },
  {
    id: 'com-702',
    empresaId: 'emp-001',
    criadoPor: 'Mariana Souza',
    criadoEm: '2026-03-01',
    status: 'Prevista',
    beneficiarioNome: 'Mariana Souza',
    clienteId: 'cli-102',
    clienteNome: 'Vanguard Pharma',
    vagaId: 'job-302',
    vagaTitulo: 'Diretor Industrial e Regulatório',
    consultorNome: 'Mariana Souza',
    tipoComissao: 'Comissão compartilhada',
    valorRecebidoVaga: 83600,
    percentual: 15,
    valorComissao: 12540,
    valorPago: 0,
    dataPrevista: '2026-04-15',
    situacao: 'Prevista',
    regraLiberacao: 'cliente_pagou'
  }
];

export const MOCK_HEADHUNTER_FINANCIAL: HeadhunterFinanceItem[] = [
  {
    id: 'fin-801',
    empresaId: 'emp-001',
    criadoPor: 'Carlos Headhunter',
    criadoEm: '2026-02-22',
    status: 'Pago',
    tipo: 'Receita',
    categoria: 'Honorários de Executive Search',
    descricao: 'Pagamento de faturamento da vaga de CTO (Grupo Nexus Tech)',
    clienteNome: 'Grupo Nexus Tech',
    vagaTitulo: 'Chief Technology Officer (CTO)',
    valor: 90000,
    dataVencimento: '2026-03-15',
    dataPagamento: '2026-03-12',
    formaPagamento: 'PIX',
    centroCusto: 'Receitas Executive Search',
    statusFinanceiro: 'Pago'
  },
  {
    id: 'fin-802',
    empresaId: 'emp-001',
    criadoPor: 'Carlos Headhunter',
    criadoEm: '2026-03-01',
    status: 'Pendente',
    tipo: 'Despesa',
    categoria: 'Software & Ferramentas Headhunter',
    descricao: 'Licença mensal do LinkedIn Recruiter Corporate',
    valor: 4200,
    dataVencimento: '2026-03-30',
    formaPagamento: 'Boleto',
    centroCusto: 'Operacional & Softwares',
    statusFinanceiro: 'Pendente'
  }
];

export const MOCK_HEADHUNTER_EXPENSES: HeadhunterExpense[] = [
  {
    id: 'exp-901',
    empresaId: 'emp-001',
    criadoPor: 'Carlos Headhunter',
    criadoEm: '2026-02-12',
    status: 'Aprovado',
    clienteId: 'cli-101',
    clienteNome: 'Grupo Nexus Tech',
    vagaId: 'job-301',
    vagaTitulo: 'Head of Growth & Performance Marketing',
    consultorNome: 'Carlos Headhunter',
    centroCusto: 'Viagens e Deslocamento',
    categoria: 'Uber',
    data: '2026-02-12',
    valor: 145.80,
    comprovanteUrl: '#',
    observacao: 'Deslocamento para reunião presencial na sede do cliente na Av. Paulista.'
  },
  {
    id: 'exp-902',
    empresaId: 'emp-001',
    criadoPor: 'Mariana Souza',
    criadoEm: '2026-02-18',
    status: 'Aprovado',
    clienteId: 'cli-102',
    clienteNome: 'Vanguard Pharma',
    vagaId: 'job-302',
    vagaTitulo: 'Diretor Industrial e Regulatório',
    consultorNome: 'Mariana Souza',
    centroCusto: 'Alimentação & Relacionamento',
    categoria: 'Alimentação',
    data: '2026-02-18',
    valor: 320.00,
    observacao: 'Almoço de alinhamento estratégico com o Diretor Geral Roberto Alencar.'
  }
];

export const MOCK_HEADHUNTER_EVENTS: HeadhunterEvent[] = [
  {
    id: 'evt-1001',
    empresaId: 'emp-001',
    criadoPor: 'Carlos Headhunter',
    criadoEm: '2026-03-20',
    status: 'Agendado',
    tipo: 'Reunião',
    titulo: 'Alinhamento de Shortlist com VP Luciana',
    clienteNome: 'Grupo Nexus Tech',
    dataHora: '2026-03-24T14:00',
    consultorNome: 'Carlos Headhunter',
    descricao: 'Apresentar pareceres dos 3 candidatos selecionados para Head of Growth.',
    concluido: false
  },
  {
    id: 'evt-1002',
    empresaId: 'emp-001',
    criadoPor: 'Mariana Souza',
    criadoEm: '2026-03-21',
    status: 'Agendado',
    tipo: 'Follow-up',
    titulo: 'Retorno sobre contrato com Solaria Energy',
    clienteNome: 'Solaria Energy Brasil',
    dataHora: '2026-03-25T11:00',
    consultorNome: 'Mariana Souza',
    descricao: 'Cobrar assinatura do aditivo comercial.',
    concluido: false
  }
];

export const MOCK_HEADHUNTER_CONTRACTS: HeadhunterContract[] = [
  {
    id: 'ctr-1101',
    empresaId: 'emp-001',
    criadoPor: 'Carlos Headhunter',
    criadoEm: '2026-01-10',
    status: 'Vigente',
    clienteId: 'cli-101',
    clienteNome: 'Grupo Nexus Tech',
    tituloContrato: 'Contrato Prestação Serviços de Executive Search 2026',
    tipo: 'Contrato Mãe',
    dataInicio: '2026-01-10',
    dataVencimento: '2027-01-10',
    valorOuPercentual: '20% do Pacote Anual por Vaga',
    assinado: true,
    documentoUrl: '#'
  },
  {
    id: 'ctr-1102',
    empresaId: 'emp-001',
    criadoPor: 'Mariana Souza',
    criadoEm: '2026-02-05',
    status: 'Vigente',
    clienteId: 'cli-102',
    clienteNome: 'Vanguard Pharma',
    tituloContrato: 'Aditivo de Exclusividade Vagas Industriais',
    tipo: 'Aditivo',
    dataInicio: '2026-02-05',
    dataVencimento: '2026-08-05',
    valorOuPercentual: '22% do Salário Mensal Bruto',
    assinado: true,
    documentoUrl: '#'
  }
];

export const MOCK_HEADHUNTER_PROPOSALS: any[] = [
  {
    id: 'prop-101',
    empresaId: 'emp-001',
    criadoPor: 'Carlos Headhunter',
    criadoEm: '2026-03-01',
    status: 'Aprovada',
    clienteId: 'cli-101',
    clienteNome: 'Grupo Nexus Tech',
    titulo: 'Proposta Comercial - CTO & Head of Tech',
    servico: 'Executive Search',
    qtdVagas: 1,
    escopo: 'Busca discreta e mapeamento de mercado para substituição de liderança de TI.',
    valor: 36000,
    modeloCobranca: 'Success Fee',
    formaPagamento: '50% na contratação / 50% após 30 dias',
    prazoEntregaDias: 30,
    prazoGarantiaDias: 90,
    validadeData: '2026-04-01'
  },
  {
    id: 'prop-102',
    empresaId: 'emp-001',
    criadoPor: 'Mariana Souza',
    criadoEm: '2026-03-12',
    status: 'Enviada',
    clienteId: 'cli-102',
    clienteNome: 'Vanguard Pharma',
    titulo: 'Proposta Comercial - Diretor Industrial',
    servico: 'Executive Search',
    qtdVagas: 1,
    escopo: 'Hunting especializado no setor farmacêutico para cargo de Direção.',
    valor: 28000,
    modeloCobranca: 'Retainer + Success',
    formaPagamento: '3x iguais sem juros via Boleto',
    prazoEntregaDias: 45,
    prazoGarantiaDias: 120,
    validadeData: '2026-04-15'
  }
];

